// Generated by   : ImageConverter 565 Online
// Generated from : wifi-25_100.png
// Time generated : Sun, 02 Oct 22 19:10:30 +0200  (Server timezone: CET)



#if defined(__AVR__)
    #include <avr/pgmspace.h>
#elif defined(__PIC32MX__)
    #define PROGMEM
#elif defined(__arm__)
    #define PROGMEM
#endif

